---
version: '3.2'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "42005:80"
    volumes:
    - type: bind
      source: ./assets
      target: /usr/local/apache2/htdocs/assets


volumes:
  deb-db:
